POST http://localhost:8080/customer
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "johndoe@domain.com"
}

###
POST http://localhost:8080/customer
Content-Type: application/json

{
  "firstName": "Mary",
  "lastName": "Smith",
  "email": "mary.smith@company.com"
}

###
GET http://localhost:8080/customer
Content-Type: application/json

### Existing customer id
GET http://localhost:8080/customer/1

### Non existing customer id
GET http://localhost:8080/customer/100
Content-Type: application/json

###
DELETE http://localhost:8080/customer/2
Content-Type: application/json